Shop/API/urls.py
from django.urls import path
from . import views
app_name = 'api'

urlpatterns = [
    # --------------------- accounts app ---------------------
    path('profile/', views.ProfileAPIView.as_view(), name='api_profile'),
    path('profile/update/', views.ProfileUpdateAPIView.as_view(), name='api_profile_update'),
    # --------------------- customers app --------------------
    path('addresses/', views.AddressListAPIView.as_view(), name='api_addresses_list'),
    path('address/create/', views.AddressCreateAPIView.as_view(), name='api_address_create'),
    path('address/update/<int:address_id>/', views.AddressUpdateAPIView.as_view(), name='api_address_update'),
    path('address/delete/<int:address_id>/', views.AddressDeleteAPIView.as_view(), name='api_address_delete'),
    # --------------------- product app ----------------------
    path('categories/', views.CategoryListAPIView.as_view(), name='api_categories_list'),
    path('products/', views.ProductListAPIView.as_view(), name='api_products_list'),
    path('product/<slug:slug>/', views.ProductDetailAPIView.as_view(), name='api_product_detail'),
    path('product/<slug:slug>/comment/create/', views.CommentCreateAPIView.as_view(), name='api_comment_create'),
    # --------------------- bucket -----------------------
    path('bucket/', views.BucketListAPIView.as_view(), name='api_bucket_list'),
    path('bucket/delete/<str:key>/', views.BucketDeleteAPIView.as_view(), name='api_bucket_delete'),
    path('bucket/download/<str:key>/', views.BucketDownloadAPIView.as_view(), name='api_bucket_download'),
    path('bucket/upload/<str:key>', views.BucketUploadAPIView.as_view(), name='api_bucket_upload'),
    # --------------------- orders app ------------------------
    path('cart/', views.CartAPIView.as_view(), name='api_cart'),
    path('cart/add/<int:product_id>/', views.CartAPIView.as_view(), name='api_cart_add'),
    path('cart/remove/<int:product_id>/', views.CartAPIView.as_view(), name='api_cart_remove'),
    path('order/create/', views.OrderCreateAPIView.as_view(), name='api_order_create'),
    path('order/checkout/<int:order_id>/', views.OrderCheckoutAPIView.as_view(), name='api_order_checkout'),
    path('order/save/<int:order_id>/', views.OrderSaveInfoAPIView.as_view(), name='api_order_save_info'),
    path('order/pay/<int:order_id>/', views.OrderPayAPIView.as_view(), name='api_order_pay'),

]

Shop/Shop/urls.py
from django.urls import re_path
from django.views.static import serve

from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from core.views import ChangeLanguageView
####################################
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="TechnoMark Shop API",
        default_version='v1.0.1',
        description="first version",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="mehdimirzaie1378@gmail.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('change-language/', ChangeLanguageView.as_view(), name='change_language'),
    path('api/auth/', include('djoser.urls')),
    path('api/auth/', include('djoser.urls.authtoken')),
    path('api/v1/', include('API.urls', namespace='api')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('product.urls', namespace='product')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('customers/', include('customers.urls', namespace='customers')),
)

urlpatterns += static(settings.STATIC_URL, documents_root=settings.STATIC_ROOT)
urlpatterns += [re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),]

urlpatterns += static(settings.MEDIA_URL, documents_root=settings.MEDIA_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }), ]

Shop/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/', views.UserProfileView.as_view(), name='user_profile'),
    path('profile/clear_image/', views.UserClearImageView.as_view(), name='user_profile_clear_image'),
    path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),


]

Shop/customers/urls.py
from django.urls import path
from . import views

app_name = 'customers'
urlpatterns = [
    path('address/create/', views.AddressCreateView.as_view(), name='address_create'),
    path('address/update/<int:address_id>', views.AddressUpdateView.as_view(), name='address_update'),
    path('address/delete/<int:address_id>', views.AddressDeleteView.as_view(), name='address_delete'),
]

Shop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    # Orders
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('udpate/<int:order_id>/', views.OrderUpdateView.as_view(), name='order_update'),
    path('details/<int:order_id>/', views.OrderDetailView.as_view(), name='order_details'),
    path('delete/<int:order_id>/', views.OrderDeleteView.as_view(), name='order_delete'),
    path('payment/<int:order_id>/', views.OrderPaymentView.as_view(), name='payment'),
    path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),
    # Shopping Cart
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),

]

Shop/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import UserManager
from datetime import datetime, timedelta
import pytz
from core.models import BaseModel
from django.utils.translation import gettext_lazy as _
from core.utils import phone_regex_validator


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=255, unique=True, verbose_name=_('Email'))
    phone_number = models.CharField(max_length=13, unique=True, validators=[phone_regex_validator],
                                    verbose_name=_('Phone Number'))
    full_name = models.CharField(max_length=50, verbose_name=_('Full Name'))
    is_active = models.BooleanField(default=True, verbose_name=_('Activation Status'))
    is_admin = models.BooleanField(default=False, verbose_name=_('Admin Status'))
    is_superuser = models.BooleanField(default=False, verbose_name=_('Superuser Status'), help_text='')

    objects = UserManager()

    class Meta:
        verbose_name = _('User')
        verbose_name_plural = _('Users')

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['email', 'full_name']

    def __str__(self):
        return self.email

    def save(self, *args, **kwargs):
        self.phone_number = '0' + self.phone_number[3:] if len(self.phone_number) == 13 else self.phone_number
        super(User, self).save(*args, **kwargs)

    @property
    def is_staff(self):
        return self.is_admin

    def role(self):
        return "Super User" if self.is_superuser else self.groups.get()

    role.short_description = _('Role')


class OtpCode(models.Model):
    phone_number = models.CharField(max_length=13, validators=[phone_regex_validator], verbose_name=_('Phone Number'))
    code = models.PositiveSmallIntegerField(verbose_name=_('Code'))
    created = models.DateTimeField(auto_now=True, verbose_name=_('Created'))

    class Meta:
        verbose_name = _('Otp Code')
        verbose_name_plural = _('Otp Codes')

    def save(self, *args, **kwargs):
        self.phone_number = '0' + self.phone_number[3:] if len(self.phone_number) == 13 else self.phone_number
        super(OtpCode, self).save(*args, **kwargs)

    @classmethod
    def is_code_available(cls, phone_number):
        counter = cls.objects.filter(phone_number=phone_number).count()
        return False if counter > 5 else True

    def __str__(self):
        return f'{self.phone_number} - {self.code} - {self.created}'

    def is_valid(self):
        utc = pytz.UTC
        expire = self.created + timedelta(minutes=32, hours=3)
        checked_on = datetime.now().replace(tzinfo=utc)
        expired_on = expire.replace(tzinfo=utc)
        if expired_on > checked_on:
            return True
        self.delete()
        return False

Shop/accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import UserRegistrationForm, VerifyCodeForm, UserLoginForm, UserProfileForm
from core.utils import random_code, send_otp_code
from .models import OtpCode, User
from django.contrib import messages
from customers.models import Customer, Address
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.utils.translation import activate


# import logging

# logger = logging.getLogger('django')


class UserRegisterView(View):
    form_class = UserRegistrationForm
    template_name = 'accounts/register.html'

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if OtpCode.is_code_available(phone_number=cd['phone']):
                rand_code = random_code()
                print(rand_code)
                send_otp_code(cd['phone'], rand_code)
                OtpCode.objects.create(phone_number=cd['phone'], code=rand_code)
                request.session['user_registration_info'] = {
                    'phone_number': cd['phone'],
                    'email': cd['email'],
                    'full_name': cd['full_name'],
                    'password': cd['password'],
                }
                messages.success(request, _('We sent you a code.'), 'success')
                return redirect('accounts:verify_code')
            else:
                messages.error(request, _('Too many attempts. Please Try again 20 minutes later.'), 'danger')
                return redirect('product:home')
        return render(request, self.template_name, {'form': form})


class UserRegisterVerifyCodeView(View):
    form_class = VerifyCodeForm

    def get(self, request):
        form = self.form_class
        return render(request, 'accounts/verify.html', {'form': form})

    def post(self, request):
        user_session = request.session['user_registration_info']
        codes = OtpCode.objects.filter(phone_number=user_session['phone_number'])
        code_instance = codes.last()
        form = self.form_class(request.POST)
        if form.is_valid():
            code = form.cleaned_data['code']
            if code == code_instance.code:
                # This method validates the code by datetime to make sure it's not expired
                if code_instance.is_valid():
                    user = User.objects.create_user(
                        phone_number=user_session['phone_number'],
                        email=user_session['email'],
                        full_name=user_session['full_name'],
                        password=user_session['password']
                    )
                    codes.delete()
                    messages.success(request, _('Your information has registered successfully'), 'success')
                    login(request, user)
                    return redirect('product:home')
                else:
                    messages.error(request, _('The code has expired. Please try again.'), 'danger')
                    return redirect('accounts:user_register')
            else:
                messages.error(request, _('This code is WRONG!'), 'danger')
                return redirect('accounts:verify_code')
        return redirect('product:home')


class UserLoginView(View):
    form_class = UserLoginForm
    template_name = 'accounts/login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('product:home')
        return super().dispatch(request, *args, **kwargs)

    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get('next')
        return super().setup(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, phone_number=cd['phone'], password=cd['password'])
            if user:
                login(request, user)
                messages.success(request, _('You logged in successfully'), 'success')
                # logger.warning(f'{user.full_name} logged in successfully')
                if self.next:
                    return redirect(self.next)
                return redirect('product:home')
            messages.error(request, _('Phone number or Password is WRONG!'), 'danger')
            # logger.error(f"User {cd['phone']} tried to login with wrong password")
        return render(request, self.template_name, {'form': form})


class UserLogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, _('You logged out successfully'), 'info')
        return redirect('product:home')


# ---------------------- User Reset Password section ------------------------

class UserPasswordResetView(auth_views.PasswordResetView):
    template_name = 'accounts/password_reset_form.html'
    success_url = reverse_lazy('accounts:password_reset_done')
    email_template_name = 'accounts/password_reset_email.html'


class UserPasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'


class UserPasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password_reset_complete')


class UserPasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'


class UserProfileView(LoginRequiredMixin, View):
    form_class = UserProfileForm
    template_name = 'accounts/profile.html'

    def setup(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            self.user = request.user
            self.customer = request.user.customer
            self.addresses = Address.objects.filter(customer=self.customer)
            self.unpaid_orders = self.customer.orders.filter(is_paid=False)
            self.paid_orders = self.customer.orders.filter(is_paid=True)
        return super().setup(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class(
            instance=self.customer,
            initial={'full_name': self.user.full_name, 'email': self.user.email,
                     'phone_number': self.user.phone_number})
        return render(
            request, self.template_name, {'form': form, 'customer': self.customer, 'addresses': self.addresses,
                                          'unpaid_orders': self.unpaid_orders, 'paid_orders': self.paid_orders})

    def post(self, request):
        form = self.form_class(request.POST, files=request.FILES, instance=self.customer)
        if form.is_valid():
            cd = form.cleaned_data
            form.save()
            self.user.full_name = cd['full_name']
            self.user.email = cd['email']
            self.user.phone_number = cd['phone_number']
            self.user.save()
            messages.success(request, _('Your information has updated successfully'), 'success')
            return redirect('accounts:user_profile')

        messages.error(request, _('Something went wrong. Correct the mistakes and try again.'), 'danger')
        return render(
            request, self.template_name,
            {'form': form, 'image': self.customer.image, 'customer': self.customer, 'addresses': self.addresses}
        )


class UserClearImageView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        customer = Customer.objects.get(user=user)
        customer.image = None
        customer.save()
        return redirect('accounts:user_profile')

Shop/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% translate 'Login' %}{% endblock %}

{% block content %}
	<form action="" method="post" class="card px-4 pt-3 pb-2 w-50 mx-auto" novalidate>
		<h3 class="text-center my-3">
			<img src="/static/img/laptop.png" width="55px" height="50px" alt="icon"> {% translate 'Technomark' %}
		</h3>
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Login" class="btn btn-primary col-5 mx-auto mt-4">
		<p class="text-center mt-5">{% translate "Don't have an account?" %} <a href="{% url 'accounts:user_register' %}">{% translate 'Register' %}</a></p>
		<p class="text-center mb-4">{% translate 'Forgot password?' %} <a href="{% url 'accounts:reset_password' %}">{% translate 'Reset Password' %}</a></p>
	</form>
{% endblock %}

Shop/accounts/templates/accounts/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol }}:// {{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

Shop/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% load i18n %}

{% load static %}

{% block title %}{% translate 'Profile Page' %}{% endblock %}

{% block content %}
	<div class="row mx-2">

		<div class="col-md-4">
			<div class="card">
				<div class="card-header">
					<h4 class="text-center mt-2">{{ customer }}</h4>
				</div>
				<div class="card-body text-center">
					<img src="{{ customer.image.url }}" class="img-fluid w-50 rounded-circle">
					<br><br>
				</div>

				<!-- Button trigger modal -->
				<button type="button" class="btn btn-outline-danger w-25 mx-auto" data-bs-toggle="modal"
								data-bs-target="#clear-image">{% translate 'Clear' %}
				</button>

				<!-- Modal -->
				<div class="modal fade" id="clear-image" tabindex="-1">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<h1 class="modal-title fs-5" id="clear-image-label">{% translate 'Clear Image' %}</h1>
								<button type="button" class="btn-close btn-danger rounded-circle" data-bs-dismiss="modal"></button>
							</div>
							<div class="modal-body">
								<p>{% translate 'Do you want to clear your image?' %}</p>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% translate 'Close' %}</button>
								<a href="{% url 'accounts:user_profile_clear_image' %}" type="button"
									 class="btn btn-danger">{% translate 'Clear' %}</a>
							</div>
						</div>
					</div>
				</div>

				<br>

				<div class="accordion" id="accordionExample">
					<div class="accordion-item">
						<h2 class="accordion-header" id="heading-profile">
							<button class="accordion-button" type="button" data-bs-toggle="collapse"
											data-bs-target="#collapse-profile"
											aria-expanded="true" aria-controls="collapse-profile">
								{% translate 'Profile Info' %}
							</button>
						</h2>
						<div id="collapse-profile" class="accordion-collapse collapse show" aria-labelledby="heading-profile"
								 data-bs-parent="#accordionExample">
							<div class="accordion-body">
								<form action="" method="post" class="px-4 py-3" enctype='multipart/form-data' novalidate>
									{% csrf_token %}
									{{ form.as_p }}
									<div class="text-center">
										<!-- Button trigger modal -->
										<button type="button" class="btn btn-primary col-5 mt-3" data-bs-toggle="modal"
														data-bs-target="#update-profile">{% translate 'Update' %}
										</button>
									</div>
									<!-- Modal -->
									<div class="modal fade" id="update-profile" tabindex="-1">
										<div class="modal-dialog bg-info">
											<div class="modal-content">
												<div class="modal-header">
													<h1 class="modal-title fs-5" id="clear-image-label">{% translate 'Update Profile' %}</h1>
													<button type="button" class="btn-close btn-danger rounded-circle"
																	data-bs-dismiss="modal"></button>
												</div>
												<div class="modal-body">
													<p>{% translate 'Do you want to update your profile?' %}</p>
												</div>
												<div class="modal-footer">
													<button type="button" class="btn btn-secondary"
																	data-bs-dismiss="modal">{% translate 'Close' %}</button>
													<button type="submit" class="btn btn-primary">{% translate 'Save Changes' %}</button>
												</div>
											</div>
										</div>
									</div>


								</form>
							</div>
						</div>
					</div>
				</div>


			</div>
		</div>

		<div class="col-md-8">

			<!-- Accordion -->
			<div class="accordion " id="accordionPanelsStayOpenExample">
				<div class="accordion-item">
					<h2 class="accordion-header" id="panelsStayOpen-headingOne">
						<button class="accordion-button" type="button" data-bs-toggle="collapse"
										data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true"
										aria-controls="panelsStayOpen-collapseOne">
							<span class="mt-2"><img src="/static/img/laptop.png" width="45px" height="40px" alt="icon">
								<span class="ms-2 fw-bold fs-4">{% translate 'Unpaid Orders' %}</span>
							</span>
						</button>
					</h2>
					<div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show"
							 aria-labelledby="panelsStayOpen-headingOne">
						<div class="accordion-body">

							{% for order in unpaid_orders %}
								<div class="row my-2">
									<div class="col-md-9">
										<p class="my-2">Order: {{ order.id }} - {{ order.created|date }} - {% trans order.status %}</p>
									</div>
									<div class="col-md-3 text-end">


										<!-- Button trigger modal -->
										<button type="button" class="btn btn-outline-danger" data-bs-toggle="modal"
														data-bs-target="#delete-order">{% translate 'Delete' %}
										</button>

										<!-- Modal -->
										<div class="modal fade" id="delete-order" tabindex="-1">
											<div class="modal-dialog">
												<div class="modal-content">
													<div class="modal-header">
														<h1 class="modal-title fs-5" id="delete-order-label">{% translate 'Delete Order' %}</h1>
														<button type="button" class="btn-close btn-danger rounded-circle"
																		data-bs-dismiss="modal"></button>
													</div>
													<div class="modal-body">
														<p class="text-start">{% translate 'Do you want to delete your order? Are you sure?' %}</p>
													</div>
													<div class="modal-footer">
														<button type="button" class="btn btn-secondary"
																		data-bs-dismiss="modal">{% translate 'Close' %}</button>
														<a href="{% url 'orders:order_delete' order.id %}" type="button"
															 class="btn btn-danger">{% translate 'Delete' %}</a>
													</div>
												</div>
											</div>
										</div>


										<a href="{% url 'orders:order_details' order.id %}"
											 class="mx-1 btn btn-outline-secondary">{% translate 'Details' %}</a>
									</div>
								</div>

							{% endfor %}
						</div>
					</div>
				</div>

				<br>


				<div class="accordion-item">
					<h2 class="accordion-header" id="panelsStayOpen-headingTwo">
						<button class="accordion-button" type="button" data-bs-toggle="collapse"
										data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="true"
										aria-controls="panelsStayOpen-collapseTwo">
							<span class="mt-2"><img src="/static/img/laptop.png" width="45px" height="40px" alt="icon">
								<span class="ms-2 fw-bold fs-4">{% translate 'Paid Orders' %}</span>
							</span>
						</button>
					</h2>
					<div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse show"
							 aria-labelledby="panelsStayOpen-headingTwo">
						<div class="accordion-body">

							{% for order in paid_orders %}
								<div class="row my-2">
									<div class="col-md-10">
										<p class="my-2">Order: {{ order.id }} - {{ order.created|date }} - {% trans order.status %}</p>
									</div>
									<div class="col-md-2 text-end">

										<a href="{% url 'orders:order_details' order.id %}"
											 class="mx-1 btn btn-outline-secondary">{% translate 'Details' %}</a>
									</div>
								</div>

							{% endfor %}
						</div>
					</div>
				</div>

				<br>

				<div class="accordion-item">
					<h2 class="accordion-header" id="panelsStayOpen-headingThree">
						<button class="accordion-button" type="button" data-bs-toggle="collapse"
										data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="true"
										aria-controls="panelsStayOpen-collapseThree">
							<span class="mt-2"><img src="/static/img/laptop.png" width="45px" height="40px" alt="icon">
								<span class="ms-2 fw-bold fs-4">{% translate 'Addresses' %}</span>
							</span>
						</button>
					</h2>
					<div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse show"
							 aria-labelledby="panelsStayOpen-headingThree">
						<div class="accordion-body">

							{% if addresses %}
								{% for address in addresses %}
									<div class="row mb-2">
										<p class="col-6">{{ address }}</p>
										<div class="col-6 text-end">
											{#									<a href="{% url 'customers:address_delete' address.id %}"#}
											{#										 class="py-1 mx-1 btn btn-outline-danger">{% translate 'Delete' %}</a>#}


											<button type="button" class="py-1 mx-1 btn btn-outline-danger" data-bs-toggle="modal"
															data-bs-target="#delete-address">{% translate 'Delete' %}
											</button>

											<div class="modal fade" id="delete-address" tabindex="-1">
												<div class="modal-dialog">
													<div class="modal-content">
														<div class="modal-header">
															<h1 class="modal-title fs-5"
																	id="delete-address-label">{% translate 'Delete Address' %}</h1>
															<button type="button" class="btn-close btn-danger rounded-circle"
																			data-bs-dismiss="modal"></button>
														</div>
														<div class="modal-body">
															<p class="text-start">{% translate 'Do you want to delete your address?' %}</p>
														</div>
														<div class="modal-footer">
															<button type="button" class="btn btn-secondary"
																			data-bs-dismiss="modal">{% translate 'Close' %}</button>
															<a href="{% url 'customers:address_delete' address.id %}"
																 class="btn btn-danger">{% translate 'Delete' %}</a>
														</div>
													</div>

												</div>
											</div>


											{#									<a href="{% url 'customers:address_update' address.id %}"#}
											{#										 class="py-1 mx-1 btn btn-outline-info">{% translate 'Update' %}</a>#}


											<button type="button" class="py-1 mx-1 btn btn-outline-info" data-bs-toggle="modal"
															data-bs-target="#update-address">{% translate 'Update' %}
											</button>

											<div class="modal fade" id="update-address" tabindex="-1">
												<div class="modal-dialog">
													<div class="modal-content">
														<div class="modal-header">
															<h1 class="modal-title fs-5"
																	id="update-address-label">{% translate 'Update Address' %}</h1>
															<button type="button" class="btn-close btn-danger rounded-circle"
																			data-bs-dismiss="modal"></button>
														</div>
														<div class="modal-body">
															<p class="text-start">{% translate 'Do you want to Update your address?' %}</p>
														</div>
														<div class="modal-footer">
															<button type="button" class="btn btn-secondary"
																			data-bs-dismiss="modal">{% translate 'Close' %}</button>
															<a href="{% url 'customers:address_update' address.id %}"
																 class="btn btn-primary">{% translate 'Update' %}</a>
														</div>
													</div>

												</div>
											</div>


										</div>
									</div>

								{% endfor %}
							{% endif %}


							<div class="text-center">
								<a href="{% url 'customers:address_create' %}"
									 class="btn btn-primary col-2">{% translate 'Add' %}</a>
							</div>

						</div>
					</div>
				</div>


			</div>

		</div>
	</div>
{% endblock %}