Shop/API/urls.py
from django.urls import path
from . import views
app_name = 'api'

urlpatterns = [
    # --------------------- accounts app ---------------------
    path('profile/', views.ProfileAPIView.as_view(), name='api_profile'),
    path('profile/update/', views.ProfileUpdateAPIView.as_view(), name='api_profile_update'),
    # --------------------- customers app --------------------
    path('addresses/', views.AddressListAPIView.as_view(), name='api_addresses_list'),
    path('address/create/', views.AddressCreateAPIView.as_view(), name='api_address_create'),
    path('address/update/<int:address_id>/', views.AddressUpdateAPIView.as_view(), name='api_address_update'),
    path('address/delete/<int:address_id>/', views.AddressDeleteAPIView.as_view(), name='api_address_delete'),
    # --------------------- product app ----------------------
    path('categories/', views.CategoryListAPIView.as_view(), name='api_categories_list'),
    path('products/', views.ProductListAPIView.as_view(), name='api_products_list'),
    path('product/<slug:slug>/', views.ProductDetailAPIView.as_view(), name='api_product_detail'),
    path('product/<slug:slug>/comment/create/', views.CommentCreateAPIView.as_view(), name='api_comment_create'),
    # --------------------- bucket -----------------------
    path('bucket/', views.BucketListAPIView.as_view(), name='api_bucket_list'),
    path('bucket/delete/<str:key>/', views.BucketDeleteAPIView.as_view(), name='api_bucket_delete'),
    path('bucket/download/<str:key>/', views.BucketDownloadAPIView.as_view(), name='api_bucket_download'),
    path('bucket/upload/<str:key>', views.BucketUploadAPIView.as_view(), name='api_bucket_upload'),
    # --------------------- orders app ------------------------
    path('cart/', views.CartAPIView.as_view(), name='api_cart'),
    path('cart/add/<int:product_id>/', views.CartAPIView.as_view(), name='api_cart_add'),
    path('cart/remove/<int:product_id>/', views.CartAPIView.as_view(), name='api_cart_remove'),
    path('order/create/', views.OrderCreateAPIView.as_view(), name='api_order_create'),
    path('order/checkout/<int:order_id>/', views.OrderCheckoutAPIView.as_view(), name='api_order_checkout'),
    path('order/save/<int:order_id>/', views.OrderSaveInfoAPIView.as_view(), name='api_order_save_info'),
    path('order/pay/<int:order_id>/', views.OrderPayAPIView.as_view(), name='api_order_pay'),

]

Shop/Shop/urls.py
from django.urls import re_path
from django.views.static import serve

from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from core.views import ChangeLanguageView
####################################
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="TechnoMark Shop API",
        default_version='v1.0.1',
        description="first version",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="mehdimirzaie1378@gmail.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('change-language/', ChangeLanguageView.as_view(), name='change_language'),
    path('api/auth/', include('djoser.urls')),
    path('api/auth/', include('djoser.urls.authtoken')),
    path('api/v1/', include('API.urls', namespace='api')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('product.urls', namespace='product')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('customers/', include('customers.urls', namespace='customers')),
)

urlpatterns += static(settings.STATIC_URL, documents_root=settings.STATIC_ROOT)
urlpatterns += [re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),]

urlpatterns += static(settings.MEDIA_URL, documents_root=settings.MEDIA_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }), ]

Shop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    # Orders
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('udpate/<int:order_id>/', views.OrderUpdateView.as_view(), name='order_update'),
    path('details/<int:order_id>/', views.OrderDetailView.as_view(), name='order_details'),
    path('delete/<int:order_id>/', views.OrderDeleteView.as_view(), name='order_delete'),
    path('payment/<int:order_id>/', views.OrderPaymentView.as_view(), name='payment'),
    path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),
    # Shopping Cart
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),

]

Shop/product/urls.py
from django.urls import path, include
from . import views

app_name = 'product'

bucket_urls = [
    path('', views.BucketView.as_view(), name='bucket'),
    path('delete_obj/<str:key>/', views.DeleteBucketObject.as_view(), name='delete_obj_bucket'),
    path('download_obj/<str:key>/', views.DownloadBucketObject.as_view(), name='download_obj_bucket'),
]

urlpatterns = [
    path('', views.LandingPageView.as_view(), name='landing'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('bucket/', include(bucket_urls)),
    path('category/<slug:category_slug>/', views.HomeView.as_view(), name='category_filter'),
    path('details/<slug:slug>/', views.ProductDetailsView.as_view(), name='product_details'),
]

Shop/product/models.py
from django.db import models
from customers.models import Customer
from core.models import BaseModel
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils.html import mark_safe
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class Category(BaseModel):
    sub_category = models.ForeignKey('self', on_delete=models.CASCADE, related_name='scategory', null=True, blank=True,
                                     verbose_name=_('Upper Category'))
    is_sub = models.BooleanField(default=False, verbose_name=_('Sub Category Status'))
    name = models.CharField(max_length=200, verbose_name=_('Category Name'))
    slug = models.SlugField(max_length=200, unique=True, verbose_name=_('Slug'))

    class Meta:
        ordering = ('is_sub', 'name',)
        verbose_name = _('category')
        verbose_name_plural = _('categories')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product:category_filter', args=(self.slug,))


class Property(BaseModel):
    key = models.CharField(max_length=120, verbose_name=_('Property Key'))
    value = models.CharField(max_length=255, unique=True, verbose_name=_('Property Value'))
    priority = models.IntegerField(default=1, verbose_name=_('Priority'))

    class Meta:
        verbose_name = _('property')
        verbose_name_plural = _('properties')
        ordering = ('priority',)

    def __str__(self):
        return f'{self.key}:{self.value}'


class Product(BaseModel):
    category = models.ManyToManyField(Category, related_name='products', verbose_name=_('Category'))
    properties = models.ManyToManyField(Property, related_name='p_products', verbose_name=_('Properties'))
    name = models.CharField(max_length=200, verbose_name=_('Product Name'))
    slug = models.SlugField(max_length=200, unique=True, verbose_name=_('Slug'))
    image = models.ImageField(default='product.png', null=True, blank=True, verbose_name=_('Image'))
    description = models.TextField(verbose_name=_('Description'))
    price_no_discount = models.PositiveIntegerField(verbose_name=_('Price without discount'))
    discount = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(90)], verbose_name=_('Discount'))
    price = models.PositiveIntegerField(verbose_name=_('Price'))
    stock = models.PositiveIntegerField(verbose_name=_('Stock'))
    is_available = models.BooleanField(null=True, blank=True, verbose_name=_('Availability Status'))

    class Meta:
        ordering = ('name',)
        verbose_name = _('product')
        verbose_name_plural = _('products')

    def save(self, *args, **kwargs):
        self.is_available = True if self.stock > 0 else False
        self.price = self.price_no_discount - self.discount * self.price_no_discount / 100
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def image_tag(self):
        return mark_safe(f'<img src="{self.image.url}" width="250" height="250" />')

    image_tag.short_description = _('Image')


class Comment(BaseModel):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='ccomments', verbose_name=_('Customer'))
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='pcomments', verbose_name=_('Product'))
    title = models.CharField(max_length=120, verbose_name=_('Title'))
    body = models.TextField(verbose_name=_('Body'))

    class Meta:
        verbose_name = _('comment')
        verbose_name_plural = _('comments')

    def __str__(self):
        return f'{self.customer} commented on {self.product}'

Shop/product/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from product.models import Comment


class ProductSearchForm(forms.Form):
    search = forms.CharField(
        max_length=100,
        required=False, label='',
        widget=forms.TextInput(attrs={'class': 'form-control col-12 py-1', 'placeholder': _('Search')}))


class UploadForm(forms.Form):
    file = forms.FileField(label='', widget=forms.FileInput(attrs={'class': 'form-control'}))


class AddCommentForm(forms.Form):
    title = forms.CharField(
        max_length=100,
        required=True, label=_('Title'))
    comment = forms.CharField(required=True, label=_('Comment'), widget=forms.Textarea(attrs={'rows': 5}))

Shop/product/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Product, Category, Comment
from .forms import ProductSearchForm, UploadForm, AddCommentForm
from orders.forms import AddToCartForm
from . import tasks
from django.contrib import messages
from utils import IsAdminUserMixin
from django.utils.translation import gettext_lazy as _
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


class LandingPageView(View):
    def get(self, request):
        return render(request, 'product/landing.html')


class HomeView(View):
    form_class = ProductSearchForm

    def get(self, request, category_slug=None):
        products = Product.objects.get_active_list().all()  # gets all objects that are active
        if request.GET.get('search'):
            products = products.filter(name__contains=request.GET['search'])

        categories = Category.objects.get_active_list().filter(is_sub=False)
        if category_slug == 'all':
            pass
        elif category_slug:
            category = Category.objects.get_active_list().get(slug=category_slug)
            products = products.filter(category=category)
        return render(request, 'product/index.html',
                      {'products': products, 'categories': categories, 'form': self.form_class})


class ProductDetailsView(View):
    form_add = AddToCartForm
    form_comment = AddCommentForm
    template_name = 'product/details.html'

    def setup(self, request, *args, **kwargs):
        self.product = Product.objects.get_active_list().get(slug=kwargs['slug'])
        self.properties = self.product.properties.all()
        self.comments = self.product.pcomments.get_active_list()
        return super().setup(request, *args, **kwargs)

    def get(self, request, slug):
        product = self.product
        properties = self.properties
        comments = self.comments
        return render(request, self.template_name, {'product': product, 'properties': properties, 'form': self.form_add,
                                                    'form_comment': self.form_comment, 'comments': comments})

    @method_decorator(login_required)
    def post(self, request, slug):
        form_comment = self.form_comment(request.POST)
        if form_comment.is_valid():
            cd = form_comment.cleaned_data
            comment = Comment.objects.create(
                customer=request.user.customer,
                product=self.product,
                title=cd['title'],
                body=cd['comment'],
                is_active=False,
            )
            messages.success(request, _('Comment added successfully'), 'info')
            return redirect('product:product_details', slug=slug)
        messages.error(request, _('Something went wrong. Check the possible errors'), 'danger')
        return render(request, self.template_name, {'form_comment': form_comment, 'product': self.product,
                                                    'properties': self.properties, 'comments': self.comments})


class BucketView(IsAdminUserMixin, View):
    template_name = 'product/bucket.html'
    form_class = UploadForm

    def get(self, request):
        objects = tasks.all_objects_task()
        form = self.form_class
        return render(request, self.template_name, {'objects': objects, 'form': form})

    def post(self, request):
        objects = tasks.all_objects_task()
        form = self.form_class(files=request.FILES)
        if form.is_valid():
            f = form.cleaned_data['file']
            tasks.upload_object_task.delay(key=form.cleaned_data['file'].name)
            messages.success(request, _('Upload will be started soon'), 'info')
            return redirect('product:bucket')
        messages.error(request, _('Something went wrong. Please try again'), 'danger')
        return render(request, self.template_name, {'objects': objects, 'form': form})


class DeleteBucketObject(IsAdminUserMixin, View):

    def get(self, request, key):
        tasks.delete_object_task.delay(key)
        messages.success(request, _('your object will be deleted soon'), 'info')
        return redirect('product:bucket')


class DownloadBucketObject(IsAdminUserMixin, View):

    def get(self, request, key):
        print(key, type(key))
        tasks.download_object_task.delay(key)
        messages.success(request, _('Download will be started soon'), 'info')
        return redirect('product:bucket')

Shop/product/templates/product/bucket.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% translate 'Bucket' %}{% endblock %}

{% block content %}


	<table class="table table-light">
		<thead>
		<tr>
			<th scope="col">#</th>
			<th scope="col">{% translate 'Name' %}</th>
			<th scope="col">{% translate 'Size' %}</th>
			<th scope="col">{% translate 'Download' %}</th>
			<th scope="col">{% translate 'Delete' %}</th>
		</tr>
		</thead>
		<tbody>
		{% for obj in objects %}
			<tr>
				<th scope="row">{{ forloop.counter }}</th>
				<td>{{ obj.Key }}</td>
				<td>{{ obj.Size|filesizeformat }}</td>
				<td><a href="{% url 'product:download_obj_bucket' obj.Key %}">{% translate 'download' %}</a></td>
				<td><a href="{% url 'product:delete_obj_bucket' obj.Key %}">{% translate 'delete' %}</a></td>
			</tr>
		{% endfor %}
		</tbody>
	</table>


	<form action="" method="post" class="input-group my-2" enctype=multipart/form-data>
		{% csrf_token %}
		{{ form }}
		<button type="submit" class="btn btn-primary px-3">{% translate 'Upload' %}</button>
	</form>

{% endblock %}

Shop/product/templates/product/details.html
{% extends 'base.html' %}

{% load i18n %}

{% load crispy_forms_filters %}

{% load static %}

{% block extra %}
	<script src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.1.0/mdb.min.js"
					integrity="sha512-oFBfx20Vuw8reYrngBlvcrgBmDcEAPE0Vv7Rb9b7JYZNHmDFdxZhiOTGm0CePa7ouSwfty9qwHQck1aVGWK5tA=="
					crossorigin="anonymous" referrerpolicy="no-referrer">

	</script>

{% endblock %}

{% block title %}{% translate 'Product Details' %}{% endblock %}

{% block content %}
	<div class="container-fluid">

		<div class="row mx-2 mt-4">


			<div class="col-md-4">
				<div class="card p-3 h-100">
					<img src="{{ product.image.url }}" class="card-img-top mx-auto my-auto" width="400px" height="400px"
							 style="object-fit: scale-down"
							 alt="{{ product.name }}">
				</div>
			</div>
			<div class="col-md-8">
				<div class="card p-5 h-100">
					<h3>{% translate 'Name' %}: {{ product }}</h3>
					<hr>
					<h4>{% translate 'Price' %}:
						<del class="text-danger "> ${{ product.price_no_discount }}</del>
						${{ product.price }}</h4>
					<hr>
					<h4>{% translate 'Discount' %}: %{{ product.discount }}</h4>
					<hr>

					<div class="row">

						{% if product.is_available %}
							<div class="col-md-6">
								<form action="{% url 'orders:cart_add' product.id %}" method="post" class="input-group mb-4">
									{% csrf_token %}
									{{ form }}
									<button type="submit" class="text-light bg-primary border-0 px-3 rounded"><i
													class="fa-solid fa-cart-plus"></i> {% translate 'Add' %}</button>
								</form>
							</div>
							<div class="col-md-6">
								{% if product.stock <= 5 %}
									<p class="alert alert-danger" style="padding: 8px 25px">
										{% translate 'Only ' %}{{ product.stock }}{% translate ' items in the stock is remaining' %}
									</p>
								{% endif %}
							</div>
						{% else %}
							<h4 class="text-danger text-center">{% translate 'Sold Out' %}</h4>
						{% endif %}
					</div>
				</div>
			</div>

			<div class="mt-2">
				<div class="bg-light mx-auto px-0 pt-2 my-2 rounded">
					<!-- Pills navs -->
					<ul class="nav nav-pills mb-2 mx-2" id="ex1" role="tablist">
						<li class="nav-item" role="presentation">
							<a class="nav-link active" id="ex1-tab-1" data-mdb-toggle="pill" href="#properties" role="tab"
								 aria-controls="properties" aria-selected="true">
								{% translate 'Properties' %}
							</a>
						</li>

						<li class="nav-item" role="presentation">
							<a class="nav-link" id="ex1-tab-2" data-mdb-toggle="pill" href="#comments" role="tab"
								 aria-controls="comments" aria-selected="false">
								{% translate 'Comments' %}
							</a>
						</li>

					</ul>
					<!-- Pills navs -->


					<!-- Pills content -->
					<div class="tab-content" id="ex1-content">
						<div class="tab-pane fade show active" id="properties" role="tabpanel" aria-labelledby="ex1-tab-1">

							<!-- Content -->
							<div>
								<div class="card h-100">
									<div class="card-header text-center" id="properties">
										<h3 class="text-center">
											<img src="/static/img/laptop.png" width="45px" height="40px"
													 alt="icon"> {% translate 'Properties' %}
										</h3>
									</div>
									<div class="card-body px-5 pt-5">
										<h3>{{ product }}</h3>
										<p>{{ product.description }}</p>
										{% for property in properties %}
											<hr>
											<p>{{ property.key }} : {{ property.value }}</p>
										{% endfor %}
									</div>
								</div>
							</div>
						</div>

						<div class="tab-pane fade" id="comments" role="tabpanel" aria-labelledby="ex1-tab-2">

							<div class="card">
								<div class="card-header text-center">
									<h3 class="text-center">
										<img src="/static/img/laptop.png" width="45px" height="40px"
												 alt="icon"> {% translate 'Comments' %}
									</h3>
								</div>
								<div class="card-body py-2 px-4">
									<div class="m-2">
										{% if comments %}
											{% for comment in comments %}
												<div class="card">
													<div class="card-header text-info">
														<div class="row">
															<h6 class="col-6">{{ comment.customer }}</h6>
															<small class="col-6 text-end">{{ comment.created }}</small>
														</div>
													</div>
													<div class="card-body">
														<h6 class="d-flex">{{ comment.title }}</h6>
														<small>{{ comment.body }}</small>
													</div>
												</div>
											{% endfor %}
										{% else %}
											<h5 class="text-center text-primary mt-4">{% translate 'No comments yet' %}</h5>
										{% endif %}
									</div>
									<hr>
									{% if request.user.is_authenticated %}
										<form action="" method="post" class="px-1 mb-2" novalidate>
											{% csrf_token %}
											{{ form_comment|crispy }}
											<div class="text-center">
												<button type="submit" class="btn btn-primary w-25">{% translate 'Send' %}</button>
											</div>
										</form>
									{% endif %}

								</div>
							</div>

						</div>
					</div>
					<!-- Pills content -->
				</div>
			</div>
		</div>

	</div>



{% endblock %}

Shop/product/templates/product/index.html
{% extends 'base.html' %}

{% load i18n %}

{% load static %}


{% block title %}{% translate 'Home' %}{% endblock %}

{% block content %}
	<div class="container-fluid">
		<div class="row mt-3 mx-3">
			<div class="col-6 justify-content-start">
				{% for category in categories %}

					<div class="btn-group">
						<a href="{{ category.get_absolute_url }}" class="btn btn-primary">{% trans category.name %}</a>
						{% if category.scategory.all %}
							<button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split"
											data-bs-toggle="dropdown" aria-expanded="false">
								<span class="visually-hidden">Toggle Dropdown</span>
							</button>

							<ul class="dropdown-menu">
								{% for sub in category.scategory.all %}
									<li><a class="dropdown-item" href="{{ sub.get_absolute_url }}">{% trans sub.name %}</a></li>
								{% endfor %}
							</ul>
						{% endif %}
					</div>


				{% endfor %}

			</div>


			<div class="col-6">
				{# Search #}
				<form action="" method="get" class="input-group mb-4">
					{{ form }}
					<button type="submit" class="btn btn-primary px-3"><i class="fa fa-search"></i></button>
				</form>
			</div>


			{% for product in products %}
				<div class="col-sm-6 col-md-4 col-lg-3 mb-4">
					<div class="card pt-0 pb-4 h-100 text-center">
						<a href="{% url 'product:product_details' product.slug %}">
							<img src="{{ product.image.url }}" class="card-img-top mx-autox px-3"
									 width="300px" height="400px"
									 style="object-fit: scale-down"
									 alt="{{ product.name }}"></a>


						<div class="row mx-2">
							<div class="col-12">
								<p class="fw-bold" style="font-size:26px">{{ product.name }}</p>
							</div>

							<div class="col-{% if not product.discount %}12{% else %}6{% endif %}">
								<h3>${{ product.price }}</h3>
							</div>

							{% if product.discount %}
								<div class="col-6">
									{#								<a href="" class="btn btn-primary{% if not product.is_available %} disabled {% endif %}"><i#}
									{#												class="fa-solid fa-cart-plus"></i> Add</a>#}
									<h3 class="text-danger">
										<del>${{ product.price_no_discount }}</del>
									</h3>
								</div>

							{% endif %}

							<br><br>


							<p class="col-12">
								{% if not product.is_available %}
									<span class="text-danger">{% translate 'Sold Out' %}</span>
								{% else %}
									<span class="text-success">{% translate 'Available' %}</span>
								{% endif %}
							</p>
							<a href="{% url 'product:product_details' product.slug %}"
								 class="col-10 mx-auto btn btn-outline-primary">{% translate 'Details' %}</a>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>


{% endblock %}

Shop/product/templates/product/landing.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% translate 'Landing Page' %}{% endblock %}

{% block extrastyle %}
	body {
	background-image: url('/static/img/landing_page.jpg');
	background-size: cover;
	background-repeat: no-repeat;
	}

{% endblock %}

{% block content %}
	<div class="container">
		<br><br><br>
		<div class="col-md-6 mx-auto my-auto justify-content-space-between">
			<div class="card bg-dark text-white text-center" style="opacity: 90%;">
				<h1 class="card-header"><img src="/static/img/laptop.png" width="55 px" height="50 px" alt="icon">
					{% translate 'TechnoMark' %}</h1>

				<div class="p-4 mb-2 bg-dark text-white">
					<h2 class="text-center text-primary">{% translate 'Welcome to your website' %}</h2>
					<br>
					<p style="font-size:20px;" dir="auto">{% translate 'The best laptops with the best prices. We hope to provide better services for you	dear customers.' %}</p>
					<br><br>
					<div class="row my-auto px-4">
						<p class="col-md-6 text-start fw-bold" style="font-size:22px" dir="auto">{% translate 'Hope you enjoy!' %}</p>
						<p class="col-md-6 text-end"><a class="btn btn-primary " href="{% url 'product:home' %}" role="button">
							{% translate 'Get Started' %}</a></p>
					</div>

				</div>
			</div>
		</div>

	</div>

{% endblock %}