Shop/API/urls.py
from django.urls import path
from . import views
app_name = 'api'

urlpatterns = [
    # --------------------- accounts app ---------------------
    path('profile/', views.ProfileAPIView.as_view(), name='api_profile'),
    path('profile/update/', views.ProfileUpdateAPIView.as_view(), name='api_profile_update'),
    # --------------------- customers app --------------------
    path('addresses/', views.AddressListAPIView.as_view(), name='api_addresses_list'),
    path('address/create/', views.AddressCreateAPIView.as_view(), name='api_address_create'),
    path('address/update/<int:address_id>/', views.AddressUpdateAPIView.as_view(), name='api_address_update'),
    path('address/delete/<int:address_id>/', views.AddressDeleteAPIView.as_view(), name='api_address_delete'),
    # --------------------- product app ----------------------
    path('categories/', views.CategoryListAPIView.as_view(), name='api_categories_list'),
    path('products/', views.ProductListAPIView.as_view(), name='api_products_list'),
    path('product/<slug:slug>/', views.ProductDetailAPIView.as_view(), name='api_product_detail'),
    path('product/<slug:slug>/comment/create/', views.CommentCreateAPIView.as_view(), name='api_comment_create'),
    # --------------------- bucket -----------------------
    path('bucket/', views.BucketListAPIView.as_view(), name='api_bucket_list'),
    path('bucket/delete/<str:key>/', views.BucketDeleteAPIView.as_view(), name='api_bucket_delete'),
    path('bucket/download/<str:key>/', views.BucketDownloadAPIView.as_view(), name='api_bucket_download'),
    path('bucket/upload/<str:key>', views.BucketUploadAPIView.as_view(), name='api_bucket_upload'),
    # --------------------- orders app ------------------------
    path('cart/', views.CartAPIView.as_view(), name='api_cart'),
    path('cart/add/<int:product_id>/', views.CartAPIView.as_view(), name='api_cart_add'),
    path('cart/remove/<int:product_id>/', views.CartAPIView.as_view(), name='api_cart_remove'),
    path('order/create/', views.OrderCreateAPIView.as_view(), name='api_order_create'),
    path('order/checkout/<int:order_id>/', views.OrderCheckoutAPIView.as_view(), name='api_order_checkout'),
    path('order/save/<int:order_id>/', views.OrderSaveInfoAPIView.as_view(), name='api_order_save_info'),
    path('order/pay/<int:order_id>/', views.OrderPayAPIView.as_view(), name='api_order_pay'),

]

Shop/Shop/urls.py
from django.urls import re_path
from django.views.static import serve

from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from core.views import ChangeLanguageView
####################################
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="TechnoMark Shop API",
        default_version='v1.0.1',
        description="first version",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="mehdimirzaie1378@gmail.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('change-language/', ChangeLanguageView.as_view(), name='change_language'),
    path('api/auth/', include('djoser.urls')),
    path('api/auth/', include('djoser.urls.authtoken')),
    path('api/v1/', include('API.urls', namespace='api')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('product.urls', namespace='product')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('customers/', include('customers.urls', namespace='customers')),
)

urlpatterns += static(settings.STATIC_URL, documents_root=settings.STATIC_ROOT)
urlpatterns += [re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),]

urlpatterns += static(settings.MEDIA_URL, documents_root=settings.MEDIA_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }), ]

Shop/customers/urls.py
from django.urls import path
from . import views

app_name = 'customers'
urlpatterns = [
    path('address/create/', views.AddressCreateView.as_view(), name='address_create'),
    path('address/update/<int:address_id>', views.AddressUpdateView.as_view(), name='address_update'),
    path('address/delete/<int:address_id>', views.AddressDeleteView.as_view(), name='address_delete'),
]

Shop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    # Orders
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('udpate/<int:order_id>/', views.OrderUpdateView.as_view(), name='order_update'),
    path('details/<int:order_id>/', views.OrderDetailView.as_view(), name='order_details'),
    path('delete/<int:order_id>/', views.OrderDeleteView.as_view(), name='order_delete'),
    path('payment/<int:order_id>/', views.OrderPaymentView.as_view(), name='payment'),
    path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),
    # Shopping Cart
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),

]

Shop/product/urls.py
from django.urls import path, include
from . import views

app_name = 'product'

bucket_urls = [
    path('', views.BucketView.as_view(), name='bucket'),
    path('delete_obj/<str:key>/', views.DeleteBucketObject.as_view(), name='delete_obj_bucket'),
    path('download_obj/<str:key>/', views.DownloadBucketObject.as_view(), name='download_obj_bucket'),
]

urlpatterns = [
    path('', views.LandingPageView.as_view(), name='landing'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('bucket/', include(bucket_urls)),
    path('category/<slug:category_slug>/', views.HomeView.as_view(), name='category_filter'),
    path('details/<slug:slug>/', views.ProductDetailsView.as_view(), name='product_details'),
]

Shop/orders/views.py
import requests
import json
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.contrib import messages
from .cart import Cart
from .forms import AddToCartForm, ChooseAddressApplyCouponForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Order, OrderItem, Coupon
from customers.models import Customer
from django.utils.translation import gettext as _
from product.models import Product


class CartView(View):
    def get(self, request):

        cart = Cart(request)
        for item in cart:
            if not item['product'].is_available:
                cart.remove(item['product'])

        if request.user.is_authenticated:
            customer = request.user.customer
            unpaid_orders = customer.orders.filter(is_paid=False)
        else:
            unpaid_orders = None

        return render(request, 'orders/cart.html', {'cart': cart, 'unpaid_orders': unpaid_orders})


class CartAddView(View):
    def post(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = AddToCartForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if cd['quantity'] > product.stock:
                messages.error(request, _('You can not add more than {} to your cart').format(product.stock), 'danger')
                return redirect('product:product_details', slug=product.slug)
            else:
                messages.success(request, _('Product added to cart successfully'), 'success')
                cart.add(product, form.cleaned_data['quantity'])
        return redirect('orders:cart')


class CartRemoveView(View):
    def get(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        return redirect('orders:cart')


class OrderCreateView(LoginRequiredMixin, View):
    def get(self, request):
        cart = Cart(request)
        for item in cart:
            if not item['product'].is_available:
                cart.remove(item['product'])

        customer = request.user.customer
        order = Order.objects.create(customer=customer)
        items_list = [OrderItem(order=order, product=item['product'], price=item['price'], quantity=item['quantity'])
                      for item in cart]
        print(items_list)
        OrderItem.objects.bulk_create(items_list)
        cart.clear()
        return redirect('orders:order_details', order.id)


class OrderUpdateView(LoginRequiredMixin, View):
    def get(self, request, order_id):
        customer = get_object_or_404(Customer, user=request.user)
        order = Order.objects.filter(customer=customer, id=order_id)

        order = order.get()
        cart = Cart(request)

        order_items = OrderItem.objects.filter(order=order)

        for item in cart:
            # if item is not in order_items create an order_item for it
            if not order_items.filter(product=item['product']).exists():
                OrderItem.objects.create(
                    order=order,
                    product=item['product'],
                    price=item['price'],
                    quantity=item['quantity'],
                )

            # if item of cart in order_items: Update the quantity of the order_item
            elif order_items.filter(product=item['product']).exists():
                order_item = order_items.get(product=item['product'])
                order_item.quantity = item['quantity']
                order_item.save()

        # if there is an order_item which is not in cart items remove order_item
        for orderitem in order_items:
            product = orderitem.product
            if str(product.id) not in cart.cart:
                orderitem.delete()

        cart.clear()
        return redirect('orders:order_details', order.id)


class OrderDetailView(LoginRequiredMixin, View):
    form_class = ChooseAddressApplyCouponForm
    template_name = 'orders/order_details.html'

    def setup(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            self.order = get_object_or_404(Order, id=kwargs['order_id'])

        return super(OrderDetailView, self).setup(request, *args, **kwargs)

    def get(self, request, order_id):
        order = self.order
        form = self.form_class(request=request, order=order)
        if order.check_address():
            return render(request, self.template_name, {'order': order, 'form': form})
        return redirect('customers:address_create')

    def post(self, request, order_id):
        order = self.order
        form = self.form_class(request.POST, request=request, order=order)
        if form.is_valid():
            address = form.cleaned_data['address']
            phone_number = form.cleaned_data['phone_number']
            order.save_address(address, phone_number)
            if form.cleaned_data['coupon']:
                coupon = Coupon.objects.get_active_list().filter(code=form.cleaned_data['coupon'])
                if coupon.exists():
                    coupon = coupon.get()
                    if coupon.is_coupon_valid():
                        order.coupon = coupon
                        order.apply_coupon()
                        order.save()
                        messages.success(request, _('Coupon applied successfully'), 'info')
                    else:
                        messages.error(request, _('Coupon is not valid'), 'danger')
                else:
                    messages.error(request, _('Coupon not found'), 'danger')
            else:
                order.coupon = None
                order.discount = 0
                order.save()
            messages.info(request, _('Order Information saved successfully'), 'info')
            return redirect('orders:order_details', order.id)
        messages.error(request, _('Please correct the error below.'), 'danger')
        return render(request, self.template_name, {'order': order, 'form': form})


class OrderDeleteView(LoginRequiredMixin, View):
    def get(self, request, order_id):
        order = get_object_or_404(Order, id=order_id)
        order.delete()
        messages.success(request, _('Order deleted successfully'), 'info')
        return redirect('orders:cart')


# ------------------------- Zarrin Pal Information --------------------------
MERCHANT = '41b3a452-5a8c-4f34-86d8-84ba6e87413d'
ZP_API_REQUEST = "https://api.zarinpal.com/pg/v4/payment/request.json"
ZP_API_VERIFY = "https://api.zarinpal.com/pg/v4/payment/verify.json"
ZP_API_STARTPAY = "https://www.zarinpal.com/pg/StartPay/{authority}"
description = _("TechnoMark Shop")
CallbackURL = "http://127.0.0.1:8000/en/orders/verify/"


class OrderPaymentView(LoginRequiredMixin, View):
    def get(self, request, order_id):
        order = get_object_or_404(Order, id=order_id)
        address = (order.city, order.body, order.postal_code, order.phone_number)
        if not all(address):
            messages.error(request, _('You must provide an address'), 'danger')
            return redirect('orders:order_details', order.id)

        items = order.items.all()
        count_of_removed_product = 0
        for item in items:
            if not item.product.is_available:
                item.delete()
                count_of_removed_product += 1

        if count_of_removed_product > 0:
            messages.error(request, _('Some of your items are sold out check your order'), 'danger')
            return redirect('orders:order_details', order.id)

        request.session['order_pay'] = {
            'order_id': order.id,
        }
        req_data = {
            "merchant_id": MERCHANT,
            "amount": order.get_total_price(),
            "callback_url": CallbackURL,
            "description": description,
            "metadata": {"mobile": request.user.phone_number, "email": request.user.email}
        }
        req_header = {"accept": "application/json", "content-type": "application/json"}
        print(json.dumps(req_data))
        req = requests.post(url=ZP_API_REQUEST, data=json.dumps(req_data), headers=req_header)
        authority = req.json()['data']['authority']
        if len(req.json()['errors']) == 0:
            return redirect(ZP_API_STARTPAY.format(authority=authority))
        else:
            e_code = req.json()['errors']['code']
            e_message = req.json()['errors']['message']
            return HttpResponse(f"Error code: {e_code}, Error Message: {e_message}")


class OrderVerifyView(LoginRequiredMixin, View):
    def get(self, request):
        order_id = request.session['order_pay']['order_id']
        order = Order.objects.get(id=int(order_id))
        t_status = request.GET.get('Status')
        t_authority = request.GET['Authority']
        if request.GET.get('Status') == 'OK':
            req_header = {"accept": "application/json",
                          "content-type": "application/json"}
            req_data = {
                "merchant_id": MERCHANT,
                "amount": order.get_total_price(),
                "authority": t_authority
            }
            req = requests.post(url=ZP_API_VERIFY, data=json.dumps(req_data), headers=req_header)
            if len(req.json()['errors']) == 0:
                t_status = req.json()['data']['code']
                if t_status == 100:
                    order.is_paid = True
                    order.save()

                    if order.coupon:
                        order.coupon.deactivate()

                    items = order.items.all()
                    product_ids = [item.product.id for item in items]
                    products = Product.objects.get_active_list().filter(id__in=product_ids)
                    print(products)
                    for item in items:
                        print(item)

Shop/orders/templates/orders/cart.html
{% extends 'base.html' %}

{% load i18n %}

{% load static %}

{% block title %}{% translate 'Cart' %}{% endblock %}


{% block content %}

    <table class="table table-info">
        <thead>
        <tr>
            <th colspan="8" class="text-center"><h3>{% translate 'Cart' %}</h3></th>
        </tr>
        <tr class="text-center">
            <th scope="col">#</th>
            <th scope="col">{% translate 'Image' %}</th>
            <th scope="col">{% translate 'Name' %}</th>
            <th scope="col">{% translate 'Quntity' %}</th>
            <th scope="col">{% translate 'Unit Price' %}</th>
            <th scope="col">{% translate 'Total Price' %}</th>
            <th scope="col">{% translate 'Discount' %}</th>
            <th scope="col">{% translate 'Remove' %}</th>

        </tr>
        </thead>

        <tbody>

        {% for item in cart %}

            <tr class="text-center">
                <th scope="row" class="align-middle">{{ forloop.counter }}</th>
                <td><a href="{% url 'product:product_details' item.product.slug %}"><img src="{{ item.image.url }}"
                                                                                         alt="{{ item.product }}"
                                                                                         width="150" height="150"
                                                                                         style="object-fit: scale-down"></a>
                </td>

                <td class="align-middle">{{ item.product }}</td>
                <td class="align-middle">{{ item.quantity }}</td>
                <td class="align-middle">$ {{ item.price }}</td>
                <td class="align-middle">$ {{ item.total_price }}</td>
                <td class="align-middle">$ {{ item.discount_price }}</td>
                <td class="align-middle"><a href="{% url 'orders:cart_remove' item.product.id %}"><img
                        src="{% static 'img/delete.png' %}" alt="delete" width="30px" height="30px"></a></td>

            </tr>


        {% endfor %}

        <tr class="fw-bold text-center">
            <td></td>
            <td>{% translate 'Total Price' %}</td>
            <td colspan="3"></td>
            <td>{{ cart.get_total_price }}</td>
            <td colspan="2"></td>
        </tr>

        <tr>
            <td colspan="8" class="text-center">
                <a href="{% url 'orders:order_create' %}"
                   class="btn btn-primary {% if cart|length == 0 %} disabled {% endif %}">{% translate 'Checkout' %}</a>

                <a href="{% url 'product:home' %}"
                   class="btn btn-success">{% translate 'Proceed Shopping' %}</a>
            </td>
        </tr>

        </tbody>
    </table>




    {% if unpaid_orders %}
        <table class="table table-warning">
            <thead>
            <tr>
                <th colspan="5"><h3 class="text-center">{% translate 'Unpaid Orders' %}</h3></th>
            </tr>
            <tr class="text-center">
                <th scope="col">{% translate 'ID' %}</th>
                <th scope="col">{% translate 'Delete' %}</th>
                <th scope="col">{% translate 'Details' %}</th>
                <th scope="col">{% translate 'Update Order With Cart' %}</th>
                <th scope="col">{% translate 'Date' %}</th>

            </tr>
            </thead>

            <tbody>

            {% for order in unpaid_orders %}

                <tr class="text-center">
                    <td class="align-middle">{{ order.id }}</td>
                    <td class="align-middle">
                        <a href="{% url 'orders:order_delete' order.id %}"
                           class="btn btn-outline-danger">{% translate 'Delete' %}</a></td>
                    <td class="align-middle">
                        <a href="{% url 'orders:order_details' order.id %}"
                           class="btn btn-outline-secondary">{% translate 'Details' %}</a></td>
                    <td class="align-middle">
                        <a href="{% url 'orders:order_update' order.id %}" class="btn btn-outline-primary">
                            {% translate 'Update' %}</a>
                    </td>
                    <td class="align-middle">{{ order.updated }}</td>

                </tr>

            {% endfor %}


            </tbody>
        </table>
    {% endif %}


{% endblock %}

Shop/orders/templates/orders/order_details.html
{% extends 'base.html' %}

{% load i18n %}

{% load static %}

{% block title %} {% translate 'Order Details' %} {% endblock %}

{% block content %}
    <div class="container col-12 card py-4 px-1" style="background-color:rgba(123,247,255,0.6)">


        <table class="table table-info w-75 mx-auto">
            <thead>
            <tr>
                {% if order.is_paid %}
                    <th colspan="4"><h3 class="text-center">{% translate 'Receipt' %}</h3></th>
                {% else %}
                    <th colspan="4"><h3 class="text-center">{% translate 'Checkout' %}</h3></th>
                {% endif %}
            </tr>


            <tr class="text-center">

                <th scope="col">{% translate 'Image' %}</th>
                <th scope="col">{% translate 'Name' %}</th>
                <th scope="col">{% translate 'Quntity' %}</th>
                <th scope="col">{% translate 'Unit Price' %}</th>


            </tr>
            </thead>

            <tbody>

            {% for item in order.items.all %}

                <tr class="text-center">

                    <td><img src="{{ item.product.image.url }}" alt="{{ item.product }}" width="100" height="100"
                             style="object-fit: scale-down"></td>

                    <td class="align-middle">{{ item.product }}</td>
                    <td class="align-middle">{{ item.quantity }}</td>
                    <td class="align-middle">$ {{ item.price }}</td>


                </tr>


            {% endfor %}

            <td colspan="1" class="text-center fw-bold py-4">{% translate 'Total Price' %}</td>
            <td colspan="1" class="text-center fw-bold py-4">{{ order.get_total_price }}</td>
            {% if order.coupon %}
                <td colspan="1" class="text-center fw-bold py-4">{% translate 'Discount' %}</td>
                <td colspan="1" class="text-center fw-bold py-4 text-danger">{{ order.discount }}%</td>
            {% else %}
                <td colspan="2"></td>
            {% endif %}


            </tbody>
        </table>



        {% if not order.is_paid %}

            <div>
                <form action="" method="post" class="w-75 card bg-white px-4 py-2 mx-auto my-2" novalidate>
                    <h3 class="text-center my-3">{% translate 'Shipping Info' %}</h3>
                    {% csrf_token %}
                    {{ form.address.label }}* &nbsp; <small>{{ form.address.help_text }}</small>
                    <br>
                    <div class="input-group">
                        {{ form.address }}
                        <a href="{% url 'customers:address_create' %}" class="btn btn-outline-primary px-2">Add New
                            Address</a>
                    </div>
                    {{ form.address.errors }}
                    <br>
                    {{ form.phone_number.label }}* &nbsp; <small>{{ form.phone_number.help_text }}</small>
                    <br>
                    {{ form.phone_number }}
                    {{ form.phone_number.errors }}
                    <br>
                    <h3 class="text-center my-1">{% translate 'Coupon Info' %}</h3>
                    {{ form.coupon.label }} &nbsp; <small>{{ form.coupon.help_text }}</small>
                    <br>
                    {{ form.coupon }}
                    {{ form.coupon.errors }}
                    <br>
                    <div class="text-center">
                        <button type="submit" class="w-25 btn btn-outline-info">{% translate 'Save' %}</button>
                        <br><br>
                        <a href="{% url 'orders:payment' order.id %}" class="btn btn-success col-2 my-2 mb-4">{% translate 'Pay' %}</a>

                    </div>
                </form>

            </div>

        {% else %}


            <table class="table table-info w-75 mx-auto">
                <thead>
                <tr>
                    <th colspan="5" class="text-center"><h3>{% translate 'Shipping Address' %}</h3></th>
                </tr>
                <tr class="text-center">
                    <th scope="col">{% translate 'City' %}</th>
                    <th scope="col">{% translate 'Address' %}</th>
                    <th scope="col">{% translate 'Postal Code' %}</th>
                    <th scope="col">{% translate 'Phone Number' %}</th>
                    <th scope="col">{% translate 'Transaction Code' %}</th>

                </tr>
                </thead>

                <tbody>

                <tr class="text-center">
                    <td>{{ order.city }}</td>
                    <td>{{ order.body }}</td>
                    <td>{{ order.postal_code }}</td>
                    <td>{{ order.phone_number }}</td>
										<td>{{ order.transaction_code }}</td>
                </tr>

                </tbody>
            </table>

        {% endif %}
    </div>
{% endblock %}