Shop/API/urls.py
from django.urls import path
from . import views
app_name = 'api'

urlpatterns = [
    # --------------------- accounts app ---------------------
    path('profile/', views.ProfileAPIView.as_view(), name='api_profile'),
    path('profile/update/', views.ProfileUpdateAPIView.as_view(), name='api_profile_update'),
    # --------------------- customers app --------------------
    path('addresses/', views.AddressListAPIView.as_view(), name='api_addresses_list'),
    path('address/create/', views.AddressCreateAPIView.as_view(), name='api_address_create'),
    path('address/update/<int:address_id>/', views.AddressUpdateAPIView.as_view(), name='api_address_update'),
    path('address/delete/<int:address_id>/', views.AddressDeleteAPIView.as_view(), name='api_address_delete'),
    # --------------------- product app ----------------------
    path('categories/', views.CategoryListAPIView.as_view(), name='api_categories_list'),
    path('products/', views.ProductListAPIView.as_view(), name='api_products_list'),
    path('product/<slug:slug>/', views.ProductDetailAPIView.as_view(), name='api_product_detail'),
    path('product/<slug:slug>/comment/create/', views.CommentCreateAPIView.as_view(), name='api_comment_create'),
    # --------------------- bucket -----------------------
    path('bucket/', views.BucketListAPIView.as_view(), name='api_bucket_list'),
    path('bucket/delete/<str:key>/', views.BucketDeleteAPIView.as_view(), name='api_bucket_delete'),
    path('bucket/download/<str:key>/', views.BucketDownloadAPIView.as_view(), name='api_bucket_download'),
    path('bucket/upload/<str:key>', views.BucketUploadAPIView.as_view(), name='api_bucket_upload'),
    # --------------------- orders app ------------------------
    path('cart/', views.CartAPIView.as_view(), name='api_cart'),
    path('cart/add/<int:product_id>/', views.CartAPIView.as_view(), name='api_cart_add'),
    path('cart/remove/<int:product_id>/', views.CartAPIView.as_view(), name='api_cart_remove'),
    path('order/create/', views.OrderCreateAPIView.as_view(), name='api_order_create'),
    path('order/checkout/<int:order_id>/', views.OrderCheckoutAPIView.as_view(), name='api_order_checkout'),
    path('order/save/<int:order_id>/', views.OrderSaveInfoAPIView.as_view(), name='api_order_save_info'),
    path('order/pay/<int:order_id>/', views.OrderPayAPIView.as_view(), name='api_order_pay'),

]

Shop/Shop/urls.py
from django.urls import re_path
from django.views.static import serve

from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from core.views import ChangeLanguageView
####################################
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="TechnoMark Shop API",
        default_version='v1.0.1',
        description="first version",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="mehdimirzaie1378@gmail.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('change-language/', ChangeLanguageView.as_view(), name='change_language'),
    path('api/auth/', include('djoser.urls')),
    path('api/auth/', include('djoser.urls.authtoken')),
    path('api/v1/', include('API.urls', namespace='api')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('product.urls', namespace='product')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('customers/', include('customers.urls', namespace='customers')),
)

urlpatterns += static(settings.STATIC_URL, documents_root=settings.STATIC_ROOT)
urlpatterns += [re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),]

urlpatterns += static(settings.MEDIA_URL, documents_root=settings.MEDIA_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }), ]

Shop/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/', views.UserProfileView.as_view(), name='user_profile'),
    path('profile/clear_image/', views.UserClearImageView.as_view(), name='user_profile_clear_image'),
    path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),


]

Shop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    # Orders
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('udpate/<int:order_id>/', views.OrderUpdateView.as_view(), name='order_update'),
    path('details/<int:order_id>/', views.OrderDetailView.as_view(), name='order_details'),
    path('delete/<int:order_id>/', views.OrderDeleteView.as_view(), name='order_delete'),
    path('payment/<int:order_id>/', views.OrderPaymentView.as_view(), name='payment'),
    path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),
    # Shopping Cart
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),

]

Shop/product/urls.py
from django.urls import path, include
from . import views

app_name = 'product'

bucket_urls = [
    path('', views.BucketView.as_view(), name='bucket'),
    path('delete_obj/<str:key>/', views.DeleteBucketObject.as_view(), name='delete_obj_bucket'),
    path('download_obj/<str:key>/', views.DownloadBucketObject.as_view(), name='download_obj_bucket'),
]

urlpatterns = [
    path('', views.LandingPageView.as_view(), name='landing'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('bucket/', include(bucket_urls)),
    path('category/<slug:category_slug>/', views.HomeView.as_view(), name='category_filter'),
    path('details/<slug:slug>/', views.ProductDetailsView.as_view(), name='product_details'),
]

Shop/templates/inc/messages.html
{% if messages %}
	{% for msg in messages %}
		<p class="alert alert-{{ msg.tags }} mx-4 my-2">{{ msg }}</p>
	{% endfor %}
{% endif %}

Shop/templates/inc/navbar.html
{% load i18n %}

<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
	<div class="ms-2 container-fluid">
		<a class="navbar-brand" href="{% url 'product:landing' %}"><img src="/static/img/laptop.png" width="34 px"
																																		height="30 px;" alt="icon">
			<span>{% translate 'TechnoMark' %}</span></a>
		<div class="collapse navbar-collapse" id="navbarNavAltMarkup">

			<div class="navbar-nav col-8">
				<a class="nav-link active" href="{% url 'product:home' %}"><i
								class="fa-solid fa-house-user"></i> {% translate 'Home' %}</a>
				{% if request.user.is_authenticated %}
					<a class="nav-link active" href="{% url 'accounts:user_logout' %}"><i
									class="fa-solid fa-right-from-bracket"></i> {% translate 'Logout' %}</a>
				{% else %}
					<a class="nav-link active" href="{% url 'accounts:user_register' %}"><i class="fa-solid fa-user-plus"></i>
						{% translate 'Register' %}</a>
					<a class="nav-link active" href="{% url 'accounts:user_login' %}"><i class="fa-solid fa-right-to-bracket"></i>
						{% translate 'Login' %}</a>
				{% endif %}
				{% if request.user.is_admin %}
					<a class="nav-link active" href="{% url 'product:bucket' %}">{% translate 'Bucket' %}</a>
				{% endif %}
				&nbsp;


				<a class="nav-link active btn btn-primary-outline" href="{% url 'change_language' %}?lang=en&next=/en/{{ request.path|slice:'4:' }}">{% translate 'EN' %}</a>
				&nbsp;


				<a class="nav-link active btn btn-primary-outline" href="{% url 'change_language' %}?lang=fa&next=/fa/{{ request.path|slice:'4:' }}">{% translate 'FA' %}</a>
			</div>
			<div class="navbar-nav col-4 justify-content-end">
				<a class="nav-link active" href="{% url 'orders:cart' %}"><i class="fa-solid fa-cart-plus"></i> {% translate 'Cart' %}
					{% if cart|length > 0 %}<span class="btn btn-danger px-2 py-0 rounded-circle">{{ cart|length }}</span>{% endif %}</a>
				{% if request.user.is_authenticated %}
					<a class="nav-link active" href="{% url 'accounts:user_profile' %}"><i class="fa-solid fa-user"></i>
						{{ request.user.full_name }} </a>
				{% endif %}
			</div>
		</div>
	</div>
</nav>